### ISSUE TITLE
RusTokenizer for python 3

### ISSUE THREAD

**Issue by sadov-m** [elmiram/RusTokenizer#1]
I've introduced some changes to make this tokenizer work for python 3.x and improved a little bit sentence segmentation:

-added lists with abbreviations and endings as the global variables so as to make it work not only for Corpus class, but for Text also;
-added the function get_sentence_segmentation for Text class to improve sentence segmentation a little bit and make the segmentation result returnable; you can still write out the results just using write_out function if you wish;
-added the opportunity to change input type for Text class: now you can enter not only a path to a file, but a text string also.

The code is available [here](https://github.com/sadov-m/readability/blob/master/get_tokens_and_sent_segmentation.py), the lists with abbreviations etc. are available [here](https://github.com/sadov-m/readability/tree/master/lists).

**Comment by elmiram** [comment]
Thanks!

The first link is broken, could you, please, update your comment with the correct link?

**Comment by sadov-m** [comment]
Done :)
Yep, it was broken because I renamed it and forgot to update the link here.

**Comment by elmiram** [comment]
Cool! And thanks again.
I added your link to README =)
